version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-
    environment:
      NODE_ENV: development # Needed if playwright is in `devDependencies`
    steps:
      - checkout # check out the code in the project directory
      - run: | 
          npm install
          npm run test
